version: '2'
services:
  ci_project-app:
    image: ci_project
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://ci_project-mssql:1433;database=ci_project
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  ci_project-mssql:
    extends:
      file: mssql.yml
      service: ci_project-mssql
